# doom emacs
export PATH="$PATH:$HOME/.emacs.d/bin"
# go tools
export PATH="$PATH:$HOME/go/bin"
export PATH="$PATH:$HOME/.local/bin"

export TERM=xterm-256color
alias ssh="TERM=xterm-256color ssh"
export LC_ALL="en_US.UTF-8"
export LANG="en_US.UTF-8"
export LANGUAGE="en_US.UTF-8"
export TERMINFO_DIRS=/usr/share/terminfo

eval "$(direnv hook zsh)"
eval "$(fnm env --use-on-cd)"

bindkey '^f' autosuggest-accept

whoport() {
  lsof -nP -i4TCP:"$1" | grep LISTEN
}

alias chrome='/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome'
alias firefox='/Applications/Firefox.app/Contents/MacOS/firefox'
alias safari='open -a Safari'

source ~/.private.zshrc 2> /dev/null
